import Head from 'next/head'
import Image from 'next/image'
import Header from '../../component/Header'
import Footer from '../../component/Footer'
import { Carousel, Button } from 'react-bootstrap';
import React, { useState } from 'react';

export default function Nav() {
    const [myName, setMyname] = useState('Lorem ipsum dolor sit amet, consectetur adipiscing elit.');

    const [firstName, lastName] = useState('Lorem ipsum dolor sit amet, consectetur adipiscing elit.');

   
    const changeef = () => {
        let val = firstName;
        (val === 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.') ? lastName('rishabhtiwari') : lastName('Lorem ipsum dolor sit amet, consectetur adipiscing elit.');
    }

    const changeName = () => {
        let val = myName;
        if (val === 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.') {
            setMyname('rishabhtiwari');
        }
        else {
            setMyname('Lorem ipsum dolor sit amet, consectetur adipiscing elit.');
        }
    }



    return (
        <div>
            <Head>
                <title>nav</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>


            <div className="headupper">
                <div className="container">
                    <div className="row">
                        <div className="col headmargin">
                            <a href="tel:1231321234" class="iconhead fas fa-phone-volume">+123 132
                                1234&nbsp;&nbsp;</a>
                            <a href="#" class="iconhead fa fa-envelope"
                            >info@zozothemes.com&nbsp;</a>
                        </div>

                        <div className="col headmargin">
                            <a className="ms-auto headicon fab fa-youtube" href="#">&nbsp;&nbsp;</a>
                            <a className="ms-auto headicon fab fa-facebook" href="#">&nbsp;&nbsp;</a>
                            <a className="ms-auto headicon fab fa-firefox-browser" href="#">&nbsp;&nbsp;</a>
                            <a className="ms-auto headicon fab fa-google-play" href="#">&nbsp;&nbsp;</a>
                        </div>
                    </div>
                </div>
            </div>

            <Header />

            <Carousel>
                <Carousel.Item interval={1000}>
                    <img
                        className="d-block w-100"
                        src="/cur1.jpg"
                        alt="Second slide"
                        width="10000" height="400"
                    />
                    <Carousel.Caption  >
                        <h3>First slide label</h3>
                        <p>{myName}</p>
                        <Button className="bcolor" onClick={changeName}>Learn More&nbsp;<i class="fas fa-long-arrow-alt-right"></i></Button>
                    </Carousel.Caption>
                </Carousel.Item>
                <Carousel.Item interval={500}>
                    <img
                        className="d-block w-100"
                        src="/cur2.jpg"
                        alt="Second slide"
                        width="10000" height="400"
                    />
                    <Carousel.Caption className="Carouselpic">
                        <h3>Second slide label</h3>
                        <p>{firstName}</p>
                        <Button className="bcolor" onClick={changeef}>Learn More&nbsp;<i class="fas fa-long-arrow-alt-right"></i></Button>
                    </Carousel.Caption>
                </Carousel.Item>

            </Carousel>

           

            <Footer />

        </div>
    )
}