import Head from 'next/head'
import Image from 'next/image'
import React from "react";
import { MDBCol, MDBContainer, MDBRow, MDBFooter } from "mdbreact";


export default function Footer() {
    return (
        <div>
            <Head>
                <title></title>
                <meta name="description" content="Generated by create next app" />
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"></link>
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="footerback">
                <MDBFooter className="font-small pt-4 mt-4">
                    <MDBContainer>
                        <MDBRow>
                            <MDBCol lg="3" md="6" sm="12" className="colfooter">
                                <strong className="colhlogo">ABOUT US</strong>
                                <hr />
                                <p>
                                    We like to provide great site with complete features
                                    what you want to impletement in your business!
                                    <br />
                                    <br />
                                    <span>Office:
                                    </span>Zozotheme.com
                                    No. 12, Ribon Building,
                                    Walse street, Australia.
                                    <br />
                                    <br />
                                    <span>Call Us:</span>
                                    +0 (123) 456-78-90 or
                                    +0 (123) 456-78-90
                                </p>
                            </MDBCol>

                            <MDBCol lg="3" md="6" sm="12" className="colfooter">
                                <strong className="colhlogo">BLOGROLL</strong>
                                <hr />
                                <p>
                                    Complete Documentations
                                    Additional Plugins & Modules
                                    <br />
                                    Child Themes
                                    <br />
                                    FAQ
                                    <br />
                                    Support Forums
                                    <br />
                                    Useful Blog
                                    <br />
                                    <br />
                                </p>
                                <strong className="colhlogo">MY ACCOUNT
                                </strong>
                                <hr />
                                My account
                                <br />
                                Order History
                                <br />
                                Shopping Cart
                            </MDBCol>

                            <MDBCol lg="3" md="6" sm="12" className="colfooter">
                                <strong className="colhlogo">LATEST NEWS</strong>
                                <hr />
                                <p>
                                    Lorem ipsum dolor sit amet,
                                    consectetur adipisicing elit.Lorem ipsum dolor sit amet,
                                    consectetur adipisicing elit.
                                </p>
                                <hr />
                                <p>
                                    Lorem ipsum dolor sit amet,
                                    consectetur adipisicing elit.Lorem ipsum dolor sit amet,
                                    consectetur adipisicing elit.
                                </p>
                                <hr />
                                <p>
                                    Lorem ipsum dolor sit amet, consectetur
                                    adipisicing elit.Lorem ipsum dolor sit amet,
                                    consectetur adipisicing elit.
                                </p>
                            </MDBCol>

                            <MDBCol lg="3" md="6" sm="12" className="colfooter">
                                <strong className="colhlogo">NEWSLETTER SIGNUP</strong>
                                <hr />
                                <p>
                                    Subscribe to Our Newsletter to get Important News,
                                    Amazing Offers & Inside Scoops:
                                </p>
                                
                                <span>TOTAL DOWNLOADS : 93550</span>
                                <br />
                                <span>HAPPY CLIENTS : 79550</span>
                                <br />
                                <br />
                                <button type="button" class="btncolor btn btn-circle btn-sm"
                                >
                                    <i class="fab fa-pinterest  fa-2x"></i>
                                </button>&nbsp;
                                <button type="button" class="btncolor btn btn-circle btn-sm"
                                ><i class="fab fa-linkedin-in fa-2x"></i>
                                </button>&nbsp;
                                <button type="button" class="btncolor btn btn-circle btn-sm"
                                >
                                    <i class="fab fa-google fa-2x"></i>
                                </button>&nbsp;
                                <button type="button" class="btncolor btn btn-circle btn-sm"
                                >
                                    <i class="fab fa-facebook-f fa-2x"></i>
                                </button>&nbsp;
                                <button type="button" class="btncolor btn btn-circle btn-sm"
                                >
                                    <i class="fab fa-twitter fa-2x" ></i>
                                </button>
                            </MDBCol>

                        </MDBRow>
                    </MDBContainer>
<hr/>
                    <div className="footer-copyright text-center py-3">
                        <MDBContainer fluid>
                            &copy; {new Date().getFullYear()} Copyright: <a href="https://www.mdbootstrap.com"> MDBootstrap.com </a>
                        </MDBContainer>
                    </div>

                </MDBFooter>

            </div>

        </div>
    )
}