import Head from 'next/head'
import Image from 'next/image'
import { Navbar,Container,Nav} from 'react-bootstrap';



export default function Header() {
    return (
        <div>
            <Head>
                <title>home</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="head" >
                <Navbar expand="lg" >
                    <Container fluid className="logopad">
                   <Image src="/logo2.jpg" width="45" height="45"></Image>
                        <Navbar.Brand className="logotitle" href="#">&nbsp;Technolitics</Navbar.Brand>
                        <Navbar.Toggle aria-controls="navbarScroll" />
                        <Navbar.Collapse id="navbarScroll">
                            <Nav
                                className="ms-auto my-2 my-lg-0"
                                style={{ maxHeight: '300px' }}
                                navbarScroll
                            >
                                <Nav.Link className="logopa" href="#action1">Home</Nav.Link>
                                <Nav.Link className="logopa" href="#action2">Pages</Nav.Link>
                                <Nav.Link className="logopa" href="#action1">Contact Us</Nav.Link>
                                <Nav.Link className="logopa" href="#action2">Gallery</Nav.Link>
                            </Nav>
                        </Navbar.Collapse>
                    </Container>
                </Navbar>
            </div>

        </div>
    )
}